# Generated by Django 4.1.5 on 2023-01-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manzil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
